# Tutorial Simon Tamayo GIT

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd
np.set_printoptions(precision=4, suppress=True)

## Load initlial matrices

In [2]:
# Adjacency matrix (the graph of the problem)
adj_mat = pd.read_csv('./adjacency_matrix.csv',sep=';',index_col=0).values
print('Adjacency matrix is:')
print(adj_mat)

# Reward matrix
reward_mat = pd.read_csv('./reward_matrix.csv',sep=';',index_col=0).values
print('Reward matrix is:')
print(reward_mat)

Adjacency matrix is:
[[0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]]
Reward matrix is:
[[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1

## Initialize Q matrix

In [3]:
# The Q matrix is the memory of the learner and it maps actions to states
nbOfStates = len(reward_mat)
states = np.arange(nbOfStates)
Q = np.zeros([nbOfStates,nbOfStates])
print('Q matrix (initial) is :')
print(Q)

Q matrix (initial) is :
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0.

## Q Learning algorithm

In [5]:
# alpha = learning rate
alpha = 1
# gamma = discount factor
gamma = 0.8

# Training iterations
# s = current state ; a = action ; snext = next state
for i in range(10000):
    s = np.random.randint(0,nbOfStates)        
    a = np.random.choice(states[adj_mat[s]==1])
    snext = a
    Q[s,a]=(1-alpha)*Q[s,a] + (alpha)*(reward_mat[s,a]+gamma*(np.max(Q[snext,:])))

# Normalize the matrix and remove impossible transitions
# print(Q)
Q = Q/np.max(Q)*adj_mat
print(np.round(Q,2))

[[0.   0.16 0.   0.   0.   0.1  0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.13 0.   0.2  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.16 0.   0.16 0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.2  0.   0.13 0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.   0.16 0.   0.   0.   0.1  0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.13 0.   0.   0.   0.   0.   0.   0.   0.08 0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.2  0.   0.   0.   0.   0.   0.   0.32 0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.13 0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.1  0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.   0.4  0.   0.   0.
  0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.32 0.   0.51 0.   0.


In [6]:
# The optimal policy is...
sln = np.argmax(Q,axis=1)

names_dict = {0:'A', 1:'B', 2:'C', 3:'D', 4:'E', 5:'F', 6:'G', 7:'H',
              8:'I', 9:'J', 10:'K', 11:'L', 12:'M', 13:'N', 14:'O', 15:'P',
              16:'Q', 17:'EX'}

sln_letters = np.vectorize(names_dict.get)(sln)

for i in range(nbOfStates):
    print('In room '+ names_dict[i]+ ' go to '+sln_letters[i])

In room A go to B
In room B go to C
In room C go to G
In room D go to C
In room E go to D
In room F go to A
In room G go to J
In room H go to E
In room I go to F
In room J go to K
In room K go to L
In room L go to M
In room M go to Q
In room N go to O
In room O go to P
In room P go to K
In room Q go to EX
In room EX go to EX
